Tutorial deep
rlberry-py/rlberry pull request #206
Opened 2022-06-01 14:21 UTC by riccardodv

We created a tutorial/quick start for deep agents (A2C).

2022-06-01 15:37 UTC, TimotheeMathieu reviewed
Looks good !
A few typo, otherwise nice.

2022-06-01 15:37 UTC, TimotheeMathieu commented on docs/basics/DeepRLTutorial/TutorialDeepRL.rst
> +beat our previous result. This time we we use a smaller learning rate
typo we we

2022-06-02 07:50 UTC, TimotheeMathieu commented on docs/basics/DeepRLTutorial/TutorialDeepRL.rst
> +
Remark : if you want to have the names of the authors in a comment, in rst this is done like that:
```
..
  Authors: Riccardo, Alena, Hector.
```

2022-06-02 09:33 UTC, mmcenta requested changes
I made some minor suggestions, let me know what you think.

2022-06-02 09:33 UTC, mmcenta commented on docs/basics/DeepRLTutorial/TutorialDeepRL.rst
> +In this tutorial we will focus on Deep Reinforcement Learning with an
I think the name is in the wrong order, it should be: "In this tutorial, we will focus on Deep Reinforcement Learning with the **Advantage Actor-Critic** algorithm."

2022-06-02 09:33 UTC, mmcenta commented on docs/basics/DeepRLTutorial/TutorialDeepRL.rst
> +As always we will consider a MDP
Maybe remove the "as always".

2022-06-02 09:33 UTC, mmcenta commented on docs/basics/DeepRLTutorial/TutorialDeepRL.rst
> +We will focus on the **CartPole-v1** environment, anyway, it might be
Suggestion: "We will focus only on the **CartPole-v1** environment, although we recommend experimenting with other environments such as **Acrobot-v1** and **MountainCar-v0**."

2022-06-02 09:33 UTC, mmcenta commented on docs/basics/DeepRLTutorial/TutorialDeepRL.rst
> +critic.
Should this be a list? Because it's displayed as a paragraph.

2022-06-02 09:33 UTC, mmcenta commented on docs/basics/DeepRLTutorial/TutorialDeepRL.rst
> +   apart from the last layer that has a linear activation.
Minor detail, but I think people are referring to MLPs more as dense neural networks nowadays.

2022-06-02 15:07 UTC, mmcenta approved these changes
LGTM!

2022-06-03 08:22 UTC, merged